timeout: 10800s
steps:
- # Compile Python interpreters from source
  name: gcr.io/cloud-builders/docker:latest
  args: ['build', '--tag=${_DOCKER_NAMESPACE}/python/interpreter-builder:${_TAG}',
         '--no-cache', '/workspace/python-interpreter-builder/']
- # Copy interpreters back to workspace
  name: ${_DOCKER_NAMESPACE}/python/interpreter-builder:${_TAG}
  args: ['cp', '/interpreters.tar.gz', '/workspace/runtime-image/interpreters.tar.gz']
- # Build base runtime image
  name: gcr.io/cloud-builders/docker:latest
  args: ['build', '--tag=${_DOCKER_NAMESPACE}/python:${_TAG}',
         '--no-cache', '/workspace/runtime-image/']
- # Validate structure of base runtime image
  name: gcr.io/gcp-runtimes/structure_test:latest
  args: [
    '-i', '${_DOCKER_NAMESPACE}/python:${_TAG}',
    '--config', '/workspace/tests/virtualenv/virtualenv_default.yaml',
    '--config', '/workspace/tests/virtualenv/virtualenv_python34.yaml',
    '--config', '/workspace/tests/virtualenv/virtualenv_python35.yaml',
    '--config', '/workspace/tests/virtualenv/virtualenv_python36.yaml',
    '--config', '/workspace/tests/no-virtualenv/no-virtualenv.yaml',
    '--config', '/workspace/tests/python2-libraries/python2-libraries.yaml',
    '--config', '/workspace/tests/python3-libraries/python3-libraries.yaml',
    '--config', '/workspace/tests/license-test/license-test.yaml',
    '-v'
    ]
- # Build image to run google client library unit tests
  name: gcr.io/cloud-builders/docker:latest
  args: ['build', '--tag=${_DOCKER_NAMESPACE}/python/tests/google-cloud-python:${_TAG}',
         '--no-cache', '/workspace/tests/google-cloud-python/']
- # Run google client library unit tests
  name: ${_DOCKER_NAMESPACE}/python/tests/google-cloud-python:${_TAG}
- # Build runtime builder image
  name: gcr.io/cloud-builders/docker:latest
  args: ['build', '--tag=${_BUILDER_DOCKER_NAMESPACE}/python/gen-dockerfile:${_TAG}',
         '--no-cache', '/workspace/builder/gen-dockerfile/']
images: [
  '${_DOCKER_NAMESPACE}/python:${_TAG}',
  '${_BUILDER_DOCKER_NAMESPACE}/python/gen-dockerfile:${_TAG}',
]
